name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Get version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

      - name: Build Firefox extension (zip)
        run: |
          mkdir -p dist
          zip -r "dist/humble-steam-check-${{ steps.version.outputs.version }}-firefox.zip" \
            manifest.json background.js content.js matcher.js \
            popup.html popup.js styles.css icons/ \
            LICENSE

      - name: Build Chrome extension (zip)
        run: |
          mkdir -p chrome-build
          cp manifest.json background.js content.js matcher.js \
            popup.html popup.js styles.css LICENSE chrome-build/
          cp -r icons chrome-build/

          cd chrome-build
          python3 -c "
          import json
          with open('manifest.json') as f:
              m = json.load(f)
          m.pop('browser_specific_settings', None)
          m['background'] = {'service_worker': 'background.js', 'type': 'module'}
          with open('manifest.json', 'w') as f:
              json.dump(m, f, indent=2)
          "

          sed -i 's/browser\.runtime/chrome.runtime/g; s/browser\.storage/chrome.storage/g' \
            background.js content.js popup.js
          cd ..

          cd chrome-build && zip -r "../dist/humble-steam-check-${{ steps.version.outputs.version }}-chrome.zip" . && cd ..

      - name: Create Forgejo Release
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          FORGEJO="https://git.deco.sh"
          REPO="signal-works/humble-steam-check"
          TAG="v${VERSION}"

          # Create release
          RELEASE_JSON=$(curl -s -X POST \
            -H "Authorization: token ${TOKEN}" \
            -H "Content-Type: application/json" \
            "${FORGEJO}/api/v1/repos/${REPO}/releases" \
            -d "{\"tag_name\":\"${TAG}\",\"name\":\"Humble Steam Check v${VERSION}\",\"body\":\"## Installation\\n\\n### Firefox\\nDownload the firefox zip and install from AMO or load temporarily via about:debugging\\n\\n### Chrome\\nDownload the chrome zip, unzip, open chrome://extensions, enable Developer Mode, click Load unpacked and select the folder\"}")

          RELEASE_ID=$(echo "$RELEASE_JSON" | jq -r '.id')
          echo "Release ID: $RELEASE_ID"

          if [ "$RELEASE_ID" = "null" ] || [ -z "$RELEASE_ID" ]; then
            echo "Failed to create release:"
            echo "$RELEASE_JSON"
            exit 1
          fi

          # Upload assets
          for file in dist/*.zip; do
            filename=$(basename "$file")
            echo "Uploading $filename..."
            curl -s -X POST \
              -H "Authorization: token ${TOKEN}" \
              -H "Content-Type: application/octet-stream" \
              "${FORGEJO}/api/v1/repos/${REPO}/releases/${RELEASE_ID}/assets?name=${filename}" \
              --data-binary "@${file}"
            echo ""
          done

          echo "Release created successfully"
