name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

      - name: Generate changelog
        id: changelog
        run: |
          # Get previous tag
          PREV_TAG=$(git tag --sort=-creatordate | head -2 | tail -1)
          CURR_TAG=${GITHUB_REF#refs/tags/}
          
          if [ "$PREV_TAG" = "$CURR_TAG" ]; then
            # First release
            CHANGES="Initial release"
          else
            CHANGES=$(git log --pretty=format:"- %s" "$PREV_TAG..$CURR_TAG" -- . ':!.forgejo' | grep -v "^- ci:" | grep -v "^- Merge" | head -20)
          fi
          
          if [ -z "$CHANGES" ]; then
            CHANGES="Bug fixes and improvements"
          fi
          
          # Write to file for AMO and release body
          echo "$CHANGES" > /tmp/changelog.txt
          echo "Changelog:"
          cat /tmp/changelog.txt

      - name: Build Firefox extension (zip)
        run: |
          mkdir -p dist
          zip -r "dist/humble-steam-check-${{ steps.version.outputs.version }}-firefox.zip" \
            manifest.json background.js content.js matcher.js \
            popup.html popup.js popup.css styles.css icons/ \
            LICENSE

      - name: Build Chrome extension (zip)
        run: |
          mkdir -p chrome-build
          cp manifest.json background.js content.js matcher.js \
            popup.html popup.js popup.css styles.css LICENSE chrome-build/
          cp -r icons chrome-build/

          cd chrome-build
          python3 -c "
          import json
          with open('manifest.json') as f:
              m = json.load(f)
          m.pop('browser_specific_settings', None)
          m['background'] = {'service_worker': 'background.js', 'type': 'module'}
          with open('manifest.json', 'w') as f:
              json.dump(m, f, indent=2)
          "

          sed -i 's/browser\.runtime/chrome.runtime/g; s/browser\.storage/chrome.storage/g' \
            background.js content.js popup.js
          cd ..

          cd chrome-build && zip -r "../dist/humble-steam-check-${{ steps.version.outputs.version }}-chrome.zip" . && cd ..

      - name: Create Forgejo Release
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          FORGEJO="https://git.deco.sh"
          REPO="signal-works/humble-steam-check"
          TAG="v${VERSION}"

          # Check if release already exists for this tag
          EXISTING=$(curl -s \
            -H "Authorization: token ${TOKEN}" \
            "${FORGEJO}/api/v1/repos/${REPO}/releases/tags/${TAG}")
          RELEASE_ID=$(echo "$EXISTING" | jq -r '.id // empty')

          if [ -n "$RELEASE_ID" ] && [ "$RELEASE_ID" != "null" ]; then
            echo "Release already exists (ID: $RELEASE_ID), deleting old assets..."
            for asset_id in $(echo "$EXISTING" | jq -r '.assets[]?.id // empty'); do
              curl -s -X DELETE \
                -H "Authorization: token ${TOKEN}" \
                "${FORGEJO}/api/v1/repos/${REPO}/releases/${RELEASE_ID}/assets/${asset_id}"
            done
          else
            echo "Creating new release..."
            RELEASE_JSON=$(curl -s -X POST \
              -H "Authorization: token ${TOKEN}" \
              -H "Content-Type: application/json" \
              "${FORGEJO}/api/v1/repos/${REPO}/releases" \
              -d "{\"tag_name\":\"${TAG}\",\"target_commitish\":\"main\",\"name\":\"Humble Steam Check v${VERSION}\",\"body\":\"## Changes\\n\\n$(cat /tmp/changelog.txt | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')\\n\\n## Installation\\n\\n### Firefox\\nInstall from [AMO](https://addons.mozilla.org/addon/humble-steam-check/) or download the firefox zip\\n\\n### Chrome\\nDownload the chrome zip, unzip, open chrome://extensions, enable Developer Mode, click Load unpacked and select the folder\"}")

            RELEASE_ID=$(echo "$RELEASE_JSON" | jq -r '.id')
            if [ "$RELEASE_ID" = "null" ] || [ -z "$RELEASE_ID" ]; then
              echo "Failed to create release:"
              echo "$RELEASE_JSON"
              exit 1
            fi
          fi
          echo "Release ID: $RELEASE_ID"

          # Upload assets
          for file in dist/*.zip; do
            filename=$(basename "$file")
            echo "Uploading $filename..."
            curl -s -X POST \
              -H "Authorization: token ${TOKEN}" \
              -H "Content-Type: application/octet-stream" \
              "${FORGEJO}/api/v1/repos/${REPO}/releases/${RELEASE_ID}/assets?name=${filename}" \
              --data-binary "@${file}"
            echo ""
          done

          echo "Release created successfully"

      - name: Submit to AMO
        env:
          AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
          AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          npm install -g web-ext
          cd dist
          unzip -o "humble-steam-check-${VERSION}-firefox.zip" -d firefox-src
          cd firefox-src
          # Create AMO metadata with changelog
          cat > amo-metadata.json << METAEOF
          {
            "version": {
              "release_notes": {
                "en-US": "$(cat /tmp/changelog.txt | sed 's/"/\\"/g' | tr '\n' ' ')"
              }
            }
          }
          METAEOF
          
          web-ext sign \
            --channel=listed \
            --api-key="$AMO_JWT_ISSUER" \
            --api-secret="$AMO_JWT_SECRET" \
            --amo-metadata=amo-metadata.json \
            || echo "AMO submission completed (may need manual review)"
